name: Test JS

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test --coverage
      
    - uses: coveralls-action@v3
      with:
        token: ${{ secrets.COVERALLS_API_TOKEN }}
